backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

# collections:
# - name: "blog" # Used in routes, e.g., /admin/collections/blog
#   label: "Blog" # Used in the UI
#   folder: "blog" # The path to the folder where the documents are stored
#   create: true # Allow users to create new documents in this collection
#   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#   fields: # The fields for each document, usually in front matter
#     - {label: "Title", name: "title", widget: "string"}
#     - {label: "Featured Image", name: "featuredImage", widget: "image"}
#     - {label: "Body", name: "body", widget: "markdown"}

collections:
# - name: "tag",
#   label: "Tag",
#   create: true
#   slug: "{{slug}}",
#   fields: 
#     - {label: "Tag", name: "tag", widget: "string"}

- name: "post" # Used in routes, e.g., /admin/collections/blog
  label: "Post" # Used in the UI
  folder: "posts" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Published", name: "published", widget: "boolean"}
    - {label: "Tags", name: "tags", widget: "list"}
    - {label: "Cover image", name: "cover_image", widget: "image"}
    - {label: "Series", name: "series", widget: "boolean"}
    - {label: "Time to read", name: "timeToRead", widget: "string"}
    - {label: "Canonical Url?", name: "canonical_url", widget: "boolean"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Content", name: "content", widget: "markdown"}
